function referencelineBerlininterp = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   REFERENCELINEBERLININTERP = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   REFERENCELINEBERLININTERP = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   referencelineBerlininterp = importfile('referenceline_Berlin_interp.csv', 2, 784);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/02/01 10:37:47

%% Initialize variables.
% Find Startrow if nargin<=2

delimiter = ';';
if nargin<=2
    [~,txt,~] = xlsread(filename);
    txt = char(txt);
    for row = 1:1:length(txt)
        if contains(txt(row,:), 'x_ref_m')
           startRow = row+1;
        end
    end 
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
referencelineBerlininterp = table(dataArray{1:end-1}, 'VariableNames', {'x_m','y_m','w_right_m','w_left_m'});

